model:
  name: 'bnneck'
  pretrained: True
  last_stride: 1


data:
  val: True
  verbose: True
  type: 'image'
  sources: ['gta_synthreid']
  targets: ['gta_synthreid']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'pad', 'random_crop']  # Normalization is always included
  save_dir: 'log/im_bnneck_triplet_val_warm_07'

loss:
  name: 'triplet'
  softmax:
    label_smooth: True

sampler:
  train_sampler: RandomIdentitySampler

train:
  optim: 'adam'
  lr: 1e-5
  weight_decay: 5e-2
  max_epoch: 60
  batch_size: 32
  print_freq: 400
  lr_scheduler: 'warmup_multi_step'
  stepsize: [20, 30, 40]

test:
  eval_flip: True
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  # evaluate: False
  eval_freq: 10
  rerank: False