on: [push, pull_request, workflow_dispatch]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: linting
      uses: alexanderdamiani/pylinter@v1.3.0
      with:
        python-root: '.'
        skip-mypy: true
        skip-isort: true
        skip-flake8: true
        flake8-flags: '--ignore=E402,F401,W504,W503 --max-line-length=120'
        mypy-flags: ''
        isort-flags: ''
        fail-on-isort: false
